app_name: VEXCLE
author: Long Hao
app_version: "2.1.0"
excel_file_name: "shot_info.xlsx"
support_formats: [
  "mov",
  "mp4",
  "avi",
  "mkv"
]
headers: [
  "thumbnail",
  "duration",
  "fps",
  "resolution",
  "frame_range",
  "filename"
]
excel_workbook_format:
  bold: True
